services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend-node:
    build:
      context: .
      dockerfile: Dockerfile.combined
    depends_on:
      - mongodb
      - backend-python
    volumes:
      - ./backend/documents:/app/backend/documents
      - ./backend/api.db:/app/backend/api.db
      - "./backend/Consolidado - Respostas Gerais.xlsx:/app/backend/Consolidado - Respostas Gerais.xlsx"
    environment:
      - PORT=5173
      - API_BASE_URL=http://backend-python:8000
      - MONGODB_URI=mongodb://mongodb:27017/cientometria
    env_file:
      - ./backend/.env
    restart: always

  backend-python:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    environment:
      - PORT=8000
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend-node
    restart: always

volumes:
  mongodb_data:
