services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb_prod
    volumes:
      - mongodb_data:/data/db
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_prod
    volumes:
      - qdrant_data_prod:/qdrant/storage
    restart: always

  backend:
    build:
      context: .
      dockerfile: docke./api-cientometria/Dockerfile
    container_name: backend_prod
    volumes:
      - ./api-cientometria/api.db:/app/api.db
      - ./api-cientometria/documents:/app/documents
    env_file:
      - env/.env.prod
    depends_on:
      - mongodb
    restart: always

  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: python_prod
    env_file:
      - env/.env.prod
    depends_on:
      - qdrant
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    container_name: frontend_prod
    ports:
      - "5173:80"
    env_file:
      - env/.env.prod
    depends_on:
      - backend
      - python
    restart: always

volumes:
  mongodb_data:
    external: true
    name: squad1_mongodb_data
  qdrant_data_prod:
