# -*- coding: utf-8 -*-
"""EXTRACTIMAGESANDLOAD0304.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msSYUjKD11JPy2RM6CaDEwfFcCxpspEr
"""

from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# CÉLULA 1 — INSTALAÇÕES (rodar uma vez)
# ============================================================
!pip install docling sentence-transformers transformers torch requests PyMuPDF opencv-python-headless Pillow -q
!sudo apt install tesseract-ocr tesseract-ocr-por tesseract-ocr-eng tesseract-ocr-spa -y -qq

# ============================================================
# PIPELINE v2 — texto + páginas com imagens (fase 1)
# ============================================================
# INSTALAÇÕES (rodar uma vez no Colab):
# !pip install docling sentence-transformers transformers torch requests PyMuPDF opencv-python-headless Pillow -q
# !sudo apt install tesseract-ocr tesseract-ocr-por tesseract-ocr-eng -y -qq

# ============================================================
# IMPORTS
# ============================================================
import os
import re
import uuid
import json
import shutil
import tempfile
import gc
from datetime import datetime
from pathlib import Path

import fitz                  # PyMuPDF
import cv2
import numpy as np
import torch
import requests
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForMaskedLM

# ============================================================
# CONFIGURAÇÕES
# ============================================================
API_BASE     = "https://sb100cientometria.optin.com.br"
API_USER     = "admin"
API_PASSWORD = "password123"

QDRANT_URL         = "https://57eb89f7-8062-4156-8bd9-761b749c9d3b.sa-east-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY     = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.o4SI3QmZtkdOUXK8KVRunQT1SymcxtZrkzUVCXmiZvQ"
COLLECTION_NAME    = "sb100"
DENSE_VECTOR_NAME  = "vetor_denso"
SPARSE_VECTOR_NAME = "vetor_esparso"

# ── Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

BASE_DIR      = Path("/content/drive/MyDrive/Pdfextractor")
DATA_DIR      = BASE_DIR / "data" / "PDFs não vetorizados"
DONE_DIR      = BASE_DIR / "data" / "PDFs concluídos"
IMG_DIR       = BASE_DIR / "data" / "Imagens"
CONTROLE_PATH = str(BASE_DIR / "indexados.json")

for d in [DATA_DIR, DONE_DIR, IMG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ============================================================
# CONTROLE DE DUPLICATAS — JSON local
# ============================================================
def carregar_indexados() -> set:
    if os.path.exists(CONTROLE_PATH):
        with open(CONTROLE_PATH, encoding="utf-8") as f:
            return set(json.load(f).keys())
    return set()

def salvar_indexado(filename: str, info: dict):
    dados = {}
    if os.path.exists(CONTROLE_PATH):
        with open(CONTROLE_PATH, encoding="utf-8") as f:
            dados = json.load(f)
    dados[filename] = info
    with open(CONTROLE_PATH, "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=2)

# ============================================================
# AUTENTICAÇÃO
# ============================================================
_token = None

def get_token():
    global _token
    resp = requests.post(
        f"{API_BASE}/api/login",
        json={"username": API_USER, "password": API_PASSWORD},
        timeout=30
    )
    resp.raise_for_status()
    data = resp.json()
    _token = next(
        (v for v in data.values() if isinstance(v, str) and v.startswith("eyJ")),
        None
    )
    if not _token:
        raise ValueError(f"Token não encontrado: {data}")
    print("✅ Token JWT obtido.")

def api_get(path, **kwargs):
    global _token
    headers = {"Authorization": f"Bearer {_token}"}
    r = requests.get(f"{API_BASE}{path}", headers=headers, timeout=120, **kwargs)
    if r.status_code == 401:
        print("  🔄 Token expirado, renovando...")
        get_token()
        headers = {"Authorization": f"Bearer {_token}"}
        r = requests.get(f"{API_BASE}{path}", headers=headers, timeout=120, **kwargs)
    r.raise_for_status()
    return r

get_token()

# ============================================================
# QDRANT — REST direto (evita problema de IPv6 no Colab)
# ============================================================
QDRANT_HEADERS = {
    "api-key": QDRANT_API_KEY,
    "Content-Type": "application/json",
}

def qdrant_get(path):
    r = requests.get(f"{QDRANT_URL}{path}", headers=QDRANT_HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def qdrant_put(path, body):
    r = requests.put(f"{QDRANT_URL}{path}", headers=QDRANT_HEADERS, json=body, timeout=60)
    r.raise_for_status()
    return r.json()

def get_points_count():
    return qdrant_get(f"/collections/{COLLECTION_NAME}")["result"]["points_count"]

def upsert_point(dense_vector, sparse_vector, payload):
    return qdrant_put(f"/collections/{COLLECTION_NAME}/points", {
        "points": [{
            "id": str(uuid.uuid4()),
            "vector": {
                DENSE_VECTOR_NAME: dense_vector,
                SPARSE_VECTOR_NAME: sparse_vector
            },
            "payload": payload
        }]
    })

# ============================================================
# MODELOS DE EMBEDDING
# ============================================================
print("🔄 Carregando modelos de embedding...")
dense_model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")
sparse_tokenizer = AutoTokenizer.from_pretrained(
    "opensearch-project/opensearch-neural-sparse-encoding-doc-v2-distill"
)
sparse_model = AutoModelForMaskedLM.from_pretrained(
    "opensearch-project/opensearch-neural-sparse-encoding-doc-v2-distill"
)
print("✅ Modelos carregados.")

def gerar_vetores_densos_batch(textos: list, batch_size: int = 32) -> list:
    embeddings = dense_model.encode(textos, batch_size=batch_size, show_progress_bar=True)
    return [emb.tolist() for emb in embeddings]

def gerar_vetor_esparso(texto: str) -> dict:
    tokens = sparse_tokenizer(
        texto, return_tensors='pt',
        max_length=512, truncation=True, padding='max_length'
    )
    with torch.no_grad():
        output = sparse_model(**tokens)
        ativacoes = torch.relu(output.logits)
        max_ativacoes, _ = ativacoes.max(dim=1)
        max_ativacoes = max_ativacoes.squeeze(0)
        indices = (max_ativacoes > 0).nonzero(as_tuple=True)[0].tolist()
        valores = max_ativacoes[indices].tolist()
    if not indices:
        indices = [0]
        valores = [0.0]
    return {"indices": indices, "values": valores}

# ============================================================
# TESSERACT SETUP
# ============================================================
candidates = [
    "/usr/share/tesseract-ocr/5/tessdata",
    "/usr/share/tesseract-ocr/4.00/tessdata",
    "/usr/share/tesseract-ocr/tessdata",
    "/usr/share/tessdata",
]
tessdata = next((p for p in candidates if os.path.isdir(p)), None)
if tessdata is None:
    tessdata = "/usr/share/tesseract-ocr/5/tessdata"
    os.makedirs(tessdata, exist_ok=True)
os.environ["TESSDATA_PREFIX"] = tessdata
needed = ["osd.traineddata", "por.traineddata", "eng.traineddata"]
missing = [f for f in needed if not os.path.isfile(os.path.join(tessdata, f))]
if missing:
    os.system("apt-get install -y -qq tesseract-ocr-por tesseract-ocr-eng 2>&1")
print(f"✅ Tesseract OK → {tessdata}")

# ============================================================
# DOCLING — PDF bytes → blocos + documento
# ============================================================
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions, TesseractCliOcrOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import PictureItem, TableItem

def converter_pdf_bytes(pdf_bytes: bytes):
    """
    Retorna (blocos, docling_document).
    blocos = lista de {texto, pagina}.
    docling_document = objeto DoclingDocument (necessário para detectar imagens).
    Se falhar: (None, None).
    """
    pipeline_options = PdfPipelineOptions()
    pipeline_options.do_ocr = True
    pipeline_options.do_table_structure = True
    pipeline_options.table_structure_options.do_cell_matching = True
    pipeline_options.ocr_options = TesseractCliOcrOptions(
        lang=["por", "eng", "spa"], force_full_page_ocr=True
    )
    pipeline_options.generate_picture_images = True

    converter = DocumentConverter(
        format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)}
    )
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(pdf_bytes)
        tmp_path = tmp.name
    try:
        doc = converter.convert(tmp_path).document
        blocos = []
        for element, _ in doc.iterate_items():
            texto = getattr(element, "text", None)
            if not texto or not texto.strip():
                continue
            page_no = None
            if hasattr(element, "prov") and element.prov:
                page_no = element.prov[0].page_no
            blocos.append({"texto": texto.strip(), "pagina": page_no})
        return (blocos, doc) if blocos else (None, None)
    except Exception as e:
        print(f"  ⚠️  Modo completo falhou ({e}). Tentando modo simples...")
        try:
            simple = PdfPipelineOptions()
            simple.do_ocr = False
            simple.do_table_structure = False
            doc = DocumentConverter(
                format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=simple)}
            ).convert(tmp_path).document
            blocos = []
            for element, _ in doc.iterate_items():
                texto = getattr(element, "text", None)
                if not texto or not texto.strip():
                    continue
                page_no = None
                if hasattr(element, "prov") and element.prov:
                    page_no = element.prov[0].page_no
                blocos.append({"texto": texto.strip(), "pagina": page_no})
            return (blocos, doc) if blocos else (None, None)
        except Exception as e2:
            print(f"  ❌ Falha total: {e2}")
            return (None, None)
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass

# ============================================================
# EXTRAÇÃO DE IMAGENS — página inteira + filtro OpenCV
#   1) Docling identifica páginas candidatas (PictureItem)
#   2) Coleta contexto textual anterior de cada imagem
#   3) Renderiza a página via PyMuPDF
#   4) OpenCV analisa se a página TEM conteúdo visual real
#      (descarta páginas só-texto que o Docling marcou errado)
# ============================================================

def pagina_tem_figura(img_path: str) -> bool:
    """
    Analisa a imagem renderizada de uma página e decide se ela
    contém figuras reais (gráficos, fotos, diagramas) ou é só texto.

    3 camadas de detecção:
      1) COR: figuras científicas quase sempre têm elementos coloridos
         (linhas, barras, áreas). Texto e logos são preto/cinza.
      2) DENSIDADE: dentro de cada blob grande, texto é esparso (~5-12%
         de pixels preenchidos), figuras são densas (>15%).
      3) DIREÇÃO DE BORDAS: texto tem bordas predominantemente horizontais
         (linhas de base das letras). Figuras têm bordas em todas direções.
    """
    img = cv2.imread(img_path)
    if img is None:
        return False

    h, w = img.shape[:2]
    area_pagina = h * w

    # ══════════════════════════════════════════════
    # CAMADA 1: DETECÇÃO DE COR
    # ══════════════════════════════════════════════
    # Gráficos de linhas, barras, pizza → linhas/áreas coloridas
    # Texto, logos P&B, caixas de texto → sem saturação
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    # Pixels com saturação significativa, não muito escuros nem claros
    mascara_cor = (hsv[:, :, 1] > 40) & (hsv[:, :, 2] > 50) & (hsv[:, :, 2] < 240)
    pct_colorido = np.sum(mascara_cor) / area_pagina

    if pct_colorido > 0.015:  # >1.5% da página com cor → tem figura
        return True

    # ══════════════════════════════════════════════
    # CAMADA 2: ANÁLISE DE BLOCOS (para figuras P&B)
    # ══════════════════════════════════════════════
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, 230, 255, cv2.THRESH_BINARY_INV)

    # Dilatação moderada para fundir elementos de uma mesma figura
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (25, 25))
    dilatada = cv2.dilate(binary, kernel, iterations=1)

    contornos, _ = cv2.findContours(dilatada, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for cnt in contornos:
        x, y, bw, bh = cv2.boundingRect(cnt)
        blob_area_ratio = (bw * bh) / area_pagina

        # Ignorar blobs pequenos (< 3% da página)
        if blob_area_ratio < 0.03:
            continue

        # ── Analisar conteúdo DENTRO do blob (imagem original binarizada)
        roi = binary[y:y+bh, x:x+bw]
        pixels_preenchidos = np.sum(roi > 0)
        fill_density = pixels_preenchidos / (bw * bh)

        # Texto em caixa/quadro: letras pequenas com espaço entre linhas
        #   → fill density baixa (~5-12%)
        # Logo pequeno dentro de área grande: também baixa density
        # Gráfico P&B: linhas grossas, eixos, pontos, barras
        #   → fill density média-alta (>15%)
        # Foto: fill density alta (>40%)
        if fill_density < 0.13:
            continue  # Esparso demais → texto ou caixa vazia

        # ── CAMADA 3: DIREÇÃO DAS BORDAS
        # Texto = bordas predominantemente horizontais (baselines das letras)
        # Figuras = bordas em múltiplas direções (eixos, linhas, curvas)
        sobel_h = cv2.Sobel(roi, cv2.CV_64F, 0, 1, ksize=3)  # bordas horizontais
        sobel_v = cv2.Sobel(roi, cv2.CV_64F, 1, 0, ksize=3)  # bordas verticais
        energia_h = np.sum(np.abs(sobel_h))
        energia_v = np.sum(np.abs(sobel_v))

        if energia_v > 0:
            ratio_hv = energia_h / energia_v
        else:
            ratio_hv = 999

        # Texto puro: ratio_hv > 2.0 (muito mais bordas horizontais)
        # Figuras: ratio_hv < 2.0 (bordas distribuídas)
        if ratio_hv > 2.0:
            continue  # Dominado por bordas horizontais → texto

        # Passou em density E em direção de bordas → é figura
        return True

    return False


def extrair_paginas_com_imagens(pdf_bytes, docling_doc, filename, img_dir, dpi=150):
    """
    1) Itera elementos do Docling na ordem de leitura
    2) Detecta PictureItem (figuras/gráficos/fotos) — NÃO tabelas
       (tabelas são convertidas para texto descritivo no chunking)
    3) Acumula texto → guarda contexto anterior
    4) Renderiza página inteira via PyMuPDF
    5) OpenCV valida se a página tem conteúdo visual real

    Retorna lista de dicts com info de cada página salva + contexto textual.
    """
    # ── Passo 1: iterar elementos, coletar páginas candidatas + contexto
    texto_acumulado = ""
    # page_no → {"n_imgs": int, "contextos": [str, ...]}
    paginas_candidatas = {}

    for element, _level in docling_doc.iterate_items():
        # Se for texto, acumula
        texto = getattr(element, "text", None)
        if texto and texto.strip():
            texto_acumulado += texto.strip() + "\n"
            continue

        # Se não for PictureItem, pula
        if not isinstance(element, PictureItem):
            continue

        # Extrair página
        page_no = None
        if hasattr(element, "prov") and element.prov:
            page_no = element.prov[0].page_no
        if page_no is None:
            continue

        # Registrar página candidata + contexto textual anterior (últimos 800 chars)
        contexto = texto_acumulado[-800:].strip() if texto_acumulado else ""
        if page_no not in paginas_candidatas:
            paginas_candidatas[page_no] = {"n_imgs": 0, "contextos": []}
        paginas_candidatas[page_no]["n_imgs"] += 1
        paginas_candidatas[page_no]["contextos"].append(contexto)

    if not paginas_candidatas:
        return []

    print(f"    📍 Páginas candidatas (Docling): {dict((k, v['n_imgs']) for k, v in sorted(paginas_candidatas.items()))}")

    # ── Passo 2: renderizar cada candidata e filtrar com OpenCV
    pdf_doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    stem = Path(filename).stem
    paginas_salvas = []
    pags_descartadas = 0

    for page_no in sorted(paginas_candidatas.keys()):
        page_idx = page_no - 1
        if page_idx < 0 or page_idx >= len(pdf_doc):
            continue

        img_filename = f"{stem}-pagina-{page_no:03d}.png"
        img_path = img_dir / img_filename

        try:
            # Renderizar
            page = pdf_doc[page_idx]
            mat = fitz.Matrix(dpi / 72.0, dpi / 72.0)
            pix = page.get_pixmap(matrix=mat)
            pix.save(str(img_path))
            larg, alt = pix.width, pix.height
            del pix
            gc.collect()

            # ── FILTRO OPENCV: página tem figura real?
            if not pagina_tem_figura(str(img_path)):
                os.remove(str(img_path))
                pags_descartadas += 1
                continue

            info = paginas_candidatas[page_no]
            n_imgs = info["n_imgs"]
            melhor_contexto = max(info["contextos"], key=len) if info["contextos"] else ""

            print(f"    ✅ p.{page_no} ({n_imgs} img) → {img_filename} ({larg}x{alt}px) ctx={len(melhor_contexto)}ch")

            paginas_salvas.append({
                "arquivo_imagem":    img_filename,
                "caminho":           str(img_path),
                "pagina_pdf":        page_no,
                "imagens_na_pagina": n_imgs,
                "largura_px":        larg,
                "altura_px":         alt,
                "dpi":               dpi,
                "contexto_textual":  melhor_contexto,
                "gemini_processado": False,
            })

        except Exception as e:
            print(f"    ❌ Falha p.{page_no}: {e}")

    pdf_doc.close()

    if pags_descartadas > 0:
        print(f"    🚫 {pags_descartadas} páginas descartadas (só texto/logos)")

    return paginas_salvas


# ============================================================
# METADADOS JSON — salva junto com as imagens
# ============================================================
def salvar_metadados_imagens(paginas_info, filename, artigo, img_dir):
    """Salva JSON com metadados bibliográficos + info de cada página com imagens."""
    stem = Path(filename).stem
    json_path = img_dir / f"{stem}-imagens-meta.json"

    titulo = (artigo.get("Título") or artigo.get("Titulo")
              or artigo.get("title") or "").strip()

    total_imgs = sum(p["imagens_na_pagina"] for p in paginas_info)

    meta = {
        "arquivo_pdf":    filename,
        "titulo":         titulo,
        "autores":        artigo.get("Autor(es)", "").strip(),
        "ano":            str(artigo.get("Ano", "")).strip(),
        "doi":            artigo.get("DOI", "").strip(),
        "periodico":      artigo.get("Título do periódico", "").strip(),
        "cultura":        artigo.get("CATEGORIA", "").strip(),
        "palavras_chave": artigo.get("Palavras-chave", "").strip(),
        "data_extracao":  datetime.now().isoformat(),
        "total_imagens_detectadas": total_imgs,
        "total_paginas_salvas":     len(paginas_info),
        "paginas": paginas_info,
    }

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    print(f"  📄 Metadados imagens → {json_path.name}")
    return str(json_path)

# ============================================================
# CONVERSÃO TABELA MARKDOWN → TEXTO DESCRITIVO
# ============================================================
def _eh_linha_tabela(texto: str) -> bool:
    """Verifica se uma linha é parte de uma tabela markdown."""
    t = texto.strip()
    return t.startswith("|") and t.endswith("|") and t.count("|") >= 3

def _eh_separador_tabela(texto: str) -> bool:
    """Verifica se é linha separadora (|---|---|)."""
    t = texto.strip().replace("|", "").replace("-", "").replace(":", "").replace(" ", "")
    return len(t) == 0

def tabela_md_para_texto(linhas_tabela: list) -> str:
    """
    Converte linhas de tabela markdown para texto descritivo.

    Entrada:
      ['| Tratamento | N (kg/ha) | Prod (t/ha) |',
       '|---|---|---|',
       '| T1 | 0 | 18.2 |',
       '| T2 | 50 | 22.5 |']

    Saída:
      'Tabela com colunas: Tratamento, N (kg/ha), Prod (t/ha).
       Tratamento T1: N (kg/ha) = 0; Prod (t/ha) = 18.2.
       Tratamento T2: N (kg/ha) = 50; Prod (t/ha) = 22.5.'
    """
    # Parsear cabeçalho e linhas de dados
    headers = []
    rows = []

    for linha in linhas_tabela:
        linha = linha.strip()
        if not linha.startswith("|"):
            continue

        celulas = [c.strip() for c in linha.split("|")[1:-1]]

        if _eh_separador_tabela(linha):
            continue
        elif not headers:
            headers = celulas
        else:
            rows.append(celulas)

    if not headers:
        # Não conseguiu parsear → retorna concatenação simples
        return " ".join(linhas_tabela)

    # ── Montar texto descritivo
    partes = []
    partes.append(f"Tabela com colunas: {', '.join(headers)}.")

    for row in rows:
        # Alinhar com headers (preencher se faltam colunas)
        while len(row) < len(headers):
            row.append("")

        if len(headers) >= 2:
            # Primeira coluna como identificador, restante como valores
            identificador = row[0]
            valores = [f"{headers[i]} = {row[i]}" for i in range(1, len(headers)) if row[i]]
            if identificador and valores:
                partes.append(f"{headers[0]} {identificador}: {'; '.join(valores)}.")
            elif valores:
                partes.append(f"{'; '.join(valores)}.")
        else:
            partes.append(f"{headers[0]}: {row[0]}.")

    return " ".join(partes)


def converter_tabelas_em_blocos(blocos: list) -> list:
    """
    Pré-processa a lista de blocos: encontra sequências de linhas
    de tabela markdown e DUPLICA — mantém o original em markdown
    E adiciona uma versão em texto descritivo logo depois.

    Isso permite busca tanto por valores exatos (markdown)
    quanto por semântica (texto descritivo).
    """
    resultado = []
    buffer_tabela = []   # acumula linhas de tabela consecutivas
    pagina_tabela = None

    def flush_tabela():
        nonlocal buffer_tabela, pagina_tabela
        if buffer_tabela:
            # 1) Manter original em markdown
            resultado.append({
                "texto": "\n".join(buffer_tabela),
                "pagina": pagina_tabela
            })
            # 2) Adicionar versão em texto descritivo
            texto_convertido = tabela_md_para_texto(buffer_tabela)
            resultado.append({
                "texto": texto_convertido,
                "pagina": pagina_tabela
            })
            buffer_tabela = []
            pagina_tabela = None

    for bloco in blocos:
        texto = bloco["texto"]
        pagina = bloco["pagina"]

        # Verificar se TODAS as linhas deste bloco são tabela
        linhas = texto.strip().splitlines()
        linhas_tabela = [l for l in linhas if _eh_linha_tabela(l) or _eh_separador_tabela(l)]

        if len(linhas_tabela) == len(linhas) and len(linhas) > 0:
            # Bloco inteiro é tabela → acumula
            buffer_tabela.extend(linhas)
            if pagina_tabela is None:
                pagina_tabela = pagina
        else:
            # Bloco normal → flush tabela acumulada, depois adiciona bloco
            flush_tabela()
            resultado.append(bloco)

    # Flush final
    flush_tabela()

    return resultado


# ============================================================
# CHUNKING — 1024 chars + 256 overlap
# ============================================================
def chunk_blocos(blocos: list) -> list:
    """Chunkeia blocos preservando número de página de origem.
    Converte tabelas markdown para texto descritivo antes de chunkar."""
    CHUNK_SIZE = 1024
    OVERLAP    = 256

    # ── Pré-processar: converter tabelas para texto
    blocos = converter_tabelas_em_blocos(blocos)

    texto_completo = ""
    mapa_paginas   = []

    for bloco in blocos:
        linha = bloco["texto"]
        if not linha.replace("-","").replace("|","").replace(" ","").strip():
            continue
        inicio_bloco = len(texto_completo)
        texto_completo += linha + "\n"
        mapa_paginas.append((inicio_bloco, len(texto_completo), bloco["pagina"]))

    def pagina_do_chunk(ini_chunk, fim_chunk):
        paginas = []
        for (ini, fim, pag) in mapa_paginas:
            if pag and ini < fim_chunk and fim > ini_chunk:
                sobreposicao = min(fim, fim_chunk) - max(ini, ini_chunk)
                paginas.append((sobreposicao, pag))
        return max(paginas, key=lambda x: x[0])[1] if paginas else None

    chunks = []
    inicio = 0

    while inicio < len(texto_completo):
        fim = inicio + CHUNK_SIZE
        if fim < len(texto_completo):
            quebra = texto_completo.rfind(" ", inicio, fim)
            if quebra == -1:
                quebra = texto_completo.rfind("\n", inicio, fim)
            if quebra != -1:
                fim = quebra

        chunk_texto = texto_completo[inicio:fim].strip()
        if chunk_texto:
            chunks.append({
                "texto":     chunk_texto,
                "pagina_pdf": pagina_do_chunk(inicio, fim)
            })

        inicio = fim - OVERLAP
        if inicio <= 0:
            break

    return chunks

# ============================================================
# MONTAR PAYLOAD COM REFERÊNCIA BIBLIOGRÁFICA COMPLETA
# ============================================================
def montar_payload(chunk: str, idx: int, filename: str, artigo: dict, pagina_pdf=None) -> dict:
    titulo = (
        artigo.get("Título") or
        artigo.get("Titulo") or
        artigo.get("title") or
        ""
    ).strip()

    return {
        "content":     chunk,
        "chunk_index": idx,
        "chunk_size":  len(chunk),
        "tipo": "tabela" if (
            chunk.startswith("Tabela com colunas:") or
            any(ln.strip().startswith("|") and ln.strip().endswith("|")
                for ln in chunk.splitlines())
        ) else "texto",

        "titulo":      titulo,
        "autores":     artigo.get("Autor(es)", "").strip(),
        "ano":         str(artigo.get("Ano", "")).strip(),
        "doi":         artigo.get("DOI", "").strip(),
        "periodico":   artigo.get("Título do periódico", "").strip(),
        "volume":      str(artigo.get("Volume", "")).strip(),
        "numero":      str(artigo.get("Número/fascículo", "")).strip(),
        "paginas":     artigo.get("Páginas", "").strip(),
        "editora":     artigo.get("Editora", "").strip(),
        "tipo_doc":    artigo.get("Tipo de documento", "").strip(),
        "instituicao": artigo.get("Instituição", "").strip(),
        "local":       artigo.get("Local", "").strip(),

        "cultura":        artigo.get("CATEGORIA", "").strip(),
        "palavras_chave": artigo.get("Palavras-chave", "").strip(),
        "nutrientes":     artigo.get("nutrientes (seleção)", "").strip(),
        "culturas":       artigo.get("culturas presentes (seleção)", "").strip(),
        "ferramentas":    artigo.get("ferramentas e técnicas (seleção)", "").strip(),
        "resumo":         artigo.get("Resumo", "").strip(),

        "pagina_pdf": pagina_pdf,
        "file":     filename,
        "ingestao": datetime.now().isoformat(),
    }

# ============================================================
# LOOP PRINCIPAL
# ============================================================

# 1. Carregar controle de duplicatas
ja_indexados = carregar_indexados()
print(f"📦 {len(ja_indexados)} arquivos já indexados (JSON local).")

# 2. Buscar metadados da API e salvar JSON
print("\n📋 Buscando metadados da API...")
r = api_get("/api/curation")
artigos = r.json()
if not isinstance(artigos, list):
    raise ValueError(f"Resposta inesperada da API: {artigos}")

# ── Todos os artigos com PDF (para match de metadados)
todos_artigos = {
    a["URL DO DOCUMENTO"].strip(): a
    for a in artigos
    if a.get("URL DO DOCUMENTO", "").strip().lower().endswith(".pdf")
}

# ── Separar aprovados e não-aprovados (para avisos)
artigos_aprovados = set()
artigos_rejeitados = set()
for nome, a in todos_artigos.items():
    aprovado = str(a.get("APROVAÇÃO CURADOR (marcar)", "")).strip().upper() == "TRUE"
    rejeitado = str(a.get("ARTIGOS REJEITADOS", "")).strip().upper() == "TRUE"
    if aprovado and not rejeitado:
        artigos_aprovados.add(nome)
    elif rejeitado:
        artigos_rejeitados.add(nome)

print(f"✅ {len(todos_artigos)} artigos na API ({len(artigos_aprovados)} aprovados, {len(artigos_rejeitados)} rejeitados)")

# ── Salvar TODOS os metadados em JSON local (atualiza toda vez)
METADADOS_PATH = str(BASE_DIR / "metadados_api.json")
with open(METADADOS_PATH, "w", encoding="utf-8") as f:
    json.dump(todos_artigos, f, ensure_ascii=False, indent=2)
print(f"💾 Metadados salvos em metadados_api.json ({len(todos_artigos)} artigos)")

# 3. Listar PDFs disponíveis no Drive
print("\n📁 Verificando PDFs no Drive...")
pdfs_locais = {}

for pasta in [DATA_DIR, DONE_DIR]:
    for pdf_path in pasta.glob("*.pdf"):
        pdfs_locais[pdf_path.name] = str(pdf_path)

print(f"✅ {len(pdfs_locais)} PDFs encontrados no Drive.")
for nome, caminho in list(pdfs_locais.items())[:5]:
    print(f"  • {nome} ({Path(caminho).parent.name}/)")
if len(pdfs_locais) > 5:
    print(f"  ... e mais {len(pdfs_locais) - 5} arquivos.")

# ── Cruzar PDFs do Drive com metadados da API
pdfs_nao_vetorizados = [f for f in pdfs_locais if Path(pdfs_locais[f]).parent == DATA_DIR]
com_meta = [f for f in pdfs_nao_vetorizados if f in todos_artigos]
sem_meta = [f for f in pdfs_nao_vetorizados if f not in todos_artigos]
nao_aprovados = [f for f in com_meta if f not in artigos_aprovados]
rejeitados = [f for f in com_meta if f in artigos_rejeitados]

print(f"\n📊 Cruzamento PDFs não vetorizados × API:")
print(f"  ✅ {len(com_meta)} PDFs COM metadados na API")
print(f"     ├─ {len(com_meta) - len(nao_aprovados)} aprovados pelo curador")
if nao_aprovados:
    print(f"     ├─ {len(nao_aprovados) - len(rejeitados)} pendentes de aprovação")
if rejeitados:
    print(f"     └─ {len(rejeitados)} rejeitados")
print(f"  ❌ {len(sem_meta)} PDFs SEM metadados na API")

if sem_meta:
    print(f"\n{'─'*60}")
    print(f"❌ PDFs SEM match na API (nome do arquivo não encontrado):")
    print(f"{'─'*60}")
    for f in sorted(sem_meta):
        print(f"  • {f}")
    print(f"{'─'*60}")

if nao_aprovados:
    print(f"\n{'─'*60}")
    print(f"⚠️  PDFs COM metadados mas NÃO aprovados pelo curador:")
    print(f"{'─'*60}")
    for f in sorted(nao_aprovados):
        status = "REJEITADO" if f in artigos_rejeitados else "PENDENTE"
        print(f"  • [{status}] {f}")
    print(f"{'─'*60}")

# 4. Filtrar: PDFs que ainda não foram indexados
novos = [f for f in pdfs_locais if f not in ja_indexados]
print(f"\n🆕 {len(novos)} PDFs novos para processar.")

if not novos:
    print("✅ Nada a fazer — todos os PDFs locais já estão indexados!")

# 5. Processar cada PDF novo
for i, filename in enumerate(novos, 1):
    artigo    = todos_artigos.get(filename, {})
    categoria = artigo.get("CATEGORIA", "").strip() or "Não especificada"
    tem_meta  = filename in todos_artigos
    aprovado  = filename in artigos_aprovados

    print(f"\n{'='*60}")
    print(f"[{i}/{len(novos)}] {filename}")
    print(f"  Categoria: {categoria}")
    if not tem_meta:
        print(f"  Metadados: ❌ NÃO encontrados na API")
    elif not aprovado:
        print(f"  Metadados: ⚠️  encontrados mas NÃO APROVADO pelo curador")
    else:
        print(f"  Metadados: ✅ encontrados e aprovados")
    print(f"  Local: {Path(pdfs_locais[filename]).parent.name}/")
    print(f"{'='*60}")

    # ── Ler PDF do Drive
    print("  📂 Lendo PDF do Drive...", end=" ", flush=True)
    try:
        with open(pdfs_locais[filename], "rb") as f:
            pdf_bytes = f.read()
        print(f"✅ ({len(pdf_bytes)/1024:.1f} KB)")
    except Exception as e:
        print(f"❌ {e}")
        continue

    # ── Converter PDF → blocos + documento Docling
    print("  🔄 Convertendo com Docling...", end=" ", flush=True)
    resultado = converter_pdf_bytes(pdf_bytes)
    if not resultado or resultado[0] is None:
        print("❌ Nenhum bloco extraído.")
        continue
    blocos, docling_doc = resultado
    print("✅")

    # ── Extrair páginas inteiras que contêm imagens
    #    Se o JSON de imagens já existe (fase anterior), pula extração
    stem = Path(filename).stem
    json_imagens_path = IMG_DIR / f"{stem}-imagens-meta.json"
    total_imgs = 0

    if json_imagens_path.exists():
        print(f"  🖼️  JSON de imagens já existe → pulando extração")
        with open(json_imagens_path, "r", encoding="utf-8") as f:
            meta_existente = json.load(f)
        total_imgs = meta_existente.get("total_imagens_detectadas", 0)
        paginas_info = meta_existente.get("paginas", [])
        print(f"  📊 {total_imgs} imagens em {len(paginas_info)} páginas (já extraídas)")
    else:
        print(f"  🖼️  Buscando páginas com imagens...")
        paginas_info = extrair_paginas_com_imagens(
            pdf_bytes, docling_doc, filename, IMG_DIR, dpi=150
        )
        if paginas_info:
            total_imgs = sum(p["imagens_na_pagina"] for p in paginas_info)
            print(f"  📊 {total_imgs} imagens em {len(paginas_info)} páginas salvas")
            salvar_metadados_imagens(paginas_info, filename, artigo, IMG_DIR)
        else:
            print(f"  ℹ️  Nenhuma imagem detectada.")

    # ── Chunking
    chunks = chunk_blocos(blocos)
    if not chunks:
        print("  ❌ Nenhum chunk gerado.")
        continue
    print(f"  ✂️  {len(chunks)} chunks gerados.")

    # ── Vetorizar denso em batch
    print(f"  🧠 Gerando vetores densos em batch ({len(chunks)} chunks)...")
    try:
        all_dense = gerar_vetores_densos_batch([c["texto"] for c in chunks], batch_size=32)
    except Exception as e:
        print(f"  ❌ Falha no batch embedding denso: {e}")
        continue

    # ── Sparse + payload + upsert
    erros_chunk = 0
    for idx, chunk in enumerate(chunks):
        chunk_texto = chunk["texto"]
        chunk_pagina = chunk["pagina_pdf"]
        print(f"  [{idx+1}/{len(chunks)}] p.{chunk_pagina} {len(chunk_texto)} chars → ", end="", flush=True)
        try:
            dense_vec  = all_dense[idx]
            print("🧠 ", end="", flush=True)

            sparse_vec = gerar_vetor_esparso(chunk_texto)
            print(f"🔍({len(sparse_vec['indices'])} tokens) → ", end="", flush=True)

            payload = montar_payload(chunk_texto, idx, filename, artigo, chunk_pagina)
            result  = upsert_point(dense_vec, sparse_vec, payload)
            print(f"📤 {result['status']}")
        except Exception as e:
            print(f"❌ {e}")
            erros_chunk += 1

    # ── Salva no JSON de controle
    salvar_indexado(filename, {
        "file":           filename,
        "titulo":         artigo.get("Título") or artigo.get("Titulo", ""),
        "autores":        artigo.get("Autor(es)", ""),
        "ano":            str(artigo.get("Ano", "")),
        "cultura":        categoria,
        "total_chunks":   len(chunks),
        "erros":          erros_chunk,
        "total_imagens":  total_imgs,
        "paginas_com_img": len(paginas_info),
        "ingestao":       datetime.now().isoformat(),
    })
    print(f"  💾 Salvo no JSON de controle.")

    # ── Move PDF para "PDFs concluídos"
    src = Path(pdfs_locais[filename])
    if src.parent != DONE_DIR:
        dst = DONE_DIR / filename
        try:
            shutil.move(str(src), str(dst))
            print(f"  📁 Movido para PDFs concluídos/")
        except Exception as e:
            print(f"  ⚠️  Não conseguiu mover: {e}")

    # ── Libera memória entre PDFs
    del pdf_bytes, blocos, docling_doc, resultado
    gc.collect()

    total = get_points_count()
    print(f"  📊 Qdrant: {total} pontos | Erros: {erros_chunk} | Imgs: {total_imgs} em {len(paginas_info)} págs")

print(f"\n🎉 Pipeline concluído! Total final: {get_points_count()} pontos.")

# ============================================================
# CÓDIGO 2 — Gemini Vision: descrever imagens
# ============================================================
# Lê os JSONs da fase 1, manda páginas pendentes para o Gemini,
# recebe descrições e atualiza o JSON.
#
# NÃO vetoriza, NÃO toca no Qdrant.
# Pode rodar várias vezes — nunca repete imagem já processada.
#
# INSTALAÇÕES:
# !pip install requests -q
# ============================================================

import os
import json
import base64
import time
from datetime import datetime
from pathlib import Path

import requests

# ============================================================
# CONFIGURAÇÕES
# ============================================================
GEMINI_API_KEY = ""  # ← colocar sua API key
GEMINI_MODEL   = "gemini-3.1-pro-preview"

# ── Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

BASE_DIR = Path("/content/drive/MyDrive/Pdfextractor")
IMG_DIR  = BASE_DIR / "data" / "Imagens"

# ── Rate limit (ajuste conforme seu tier)
GEMINI_DELAY = 5  # segundos entre chamadas

# ============================================================
# GEMINI VISION — chamada REST
# ============================================================
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"

GEMINI_PROMPT_IMAGEM = """Você é um especialista em agronomia e ciências agrárias. Sua tarefa é extrair o MÁXIMO de informação quantitativa e qualitativa de cada figura presente nesta página de artigo científico.

Contexto textual extraído da mesma região do PDF:
\"\"\"{contexto}\"\"\"

Metadados do artigo:
- Título: {titulo}
- Autores: {autores}
- Cultura/Categoria: {cultura}

INSTRUÇÕES DETALHADAS:

Para GRÁFICOS (linhas, barras, scatter, pizza):
- Leia TODOS os valores dos eixos X e Y com suas unidades exatas
- Identifique CADA série/linha/barra pela legenda (ex: "Tratamento 1", "Variedade IAC-385")
- Extraia TODOS os pontos de dados visíveis com seus valores numéricos aproximados
- Identifique valores máximos, mínimos e pontos ótimos
- Descreva a tendência de cada série (crescente, decrescente, quadrática, estável)
- Se houver barras de erro ou letras de significância estatística, inclua
- Se houver equação de regressão (R², y=ax+b), transcreva

Para FOTOS:
- Descreva o que aparece com detalhes agronômicos (sintomas, estágio fenológico, parte da planta)
- Identifique tratamentos se houver comparação visual

Para DIAGRAMAS/MAPAS:
- Descreva a estrutura e as relações apresentadas
- Extraia valores numéricos se presentes

Para CADA figura encontrada na página, responda em JSON (lista):
[
  {{
    "tipo": "grafico_linhas|grafico_barras|grafico_pizza|scatter|tabela_imagem|foto|diagrama|mapa|outro",
    "titulo_figura": "Título ou legenda da figura como aparece no PDF (ex: Figura 3. Produtividade...)",
    "descricao": "Descrição detalhada de 4-8 frases. Inclua: o que o gráfico mostra, quais tratamentos/variáveis são comparados, qual a faixa de valores no eixo X e Y, e como os dados se comportam.",
    "variaveis": ["nome completo da variável X com unidade", "nome completo da variável Y com unidade"],
    "unidades": ["unidade X", "unidade Y"],
    "series_dados": ["nome da série 1 (legenda)", "nome da série 2"],
    "dados_extraidos": [
      {{"serie": "nome", "x": "valor_x", "y": "valor_y"}},
      {{"serie": "nome", "x": "valor_x", "y": "valor_y"}}
    ],
    "valor_maximo": "Descreva o ponto máximo observado com valores exatos (ex: produtividade máxima de 42.5 t/ha na dose de 120 kg N/ha)",
    "valor_minimo": "Descreva o ponto mínimo observado com valores exatos",
    "ponto_otimo": "Se identificável, descreva a dose/concentração/valor ótimo recomendado",
    "tendencia": "Descrição da tendência matemática (linear crescente, quadrática com pico em X, logarítmica, sem diferença significativa entre tratamentos, etc.)",
    "equacao_regressao": "Se visível no gráfico, transcreva a equação (ex: y = -0.002x² + 0.48x + 15.3, R² = 0.94)",
    "significancia_estatistica": "Se houver letras (a, b, c) ou asteriscos (* **) de significância, descreva quais tratamentos diferem",
    "conclusao_principal": "Conclusão prática em 1-2 frases que um agrônomo usaria para recomendar uma dose/prática"
  }}
]

Se a página NÃO contiver nenhuma figura real (só texto, logos ou decoração), responda:
[]

IMPORTANTE: Extraia valores numéricos EXATOS sempre que visíveis. É melhor um valor aproximado lido do gráfico do que nenhum valor.

Responda APENAS o JSON, sem markdown, sem ```."""


GEMINI_PROMPT_TABELA = """Você é um especialista em agronomia e ciências agrárias. Sua tarefa é extrair o MÁXIMO de informação quantitativa de cada tabela presente nesta página de artigo científico.

Contexto textual extraído da mesma região do PDF:
\"\"\"{contexto}\"\"\"

Texto markdown extraído da(s) tabela(s) pelo OCR (pode conter erros):
\"\"\"{tabelas_md}\"\"\"

Metadados do artigo:
- Título: {titulo}
- Autores: {autores}
- Cultura/Categoria: {cultura}

INSTRUÇÕES DETALHADAS:

- Identifique TODAS as colunas e suas unidades
- Identifique TODOS os tratamentos/linhas
- Extraia os valores numéricos mais importantes de cada célula
- Identifique qual tratamento teve o melhor e o pior resultado
- Se houver letras de significância estatística (a, b, c), descreva quais tratamentos diferem
- Se houver médias, desvios padrão ou coeficientes de variação, inclua
- Descreva relações dose-resposta se aplicável

Para CADA tabela encontrada na página, responda em JSON (lista):
[
  {{
    "tipo": "tabela",
    "titulo_figura": "Título da tabela como aparece no PDF (ex: Tabela 2. Teores foliares...)",
    "descricao": "Descrição detalhada de 5-8 frases. Inclua: quantas linhas e colunas, quais tratamentos são comparados, quais parâmetros são medidos, faixas de valores observados, e quais tratamentos se destacaram.",
    "variaveis": ["variável 1 (unidade)", "variável 2 (unidade)", "variável 3 (unidade)"],
    "unidades": ["unidade 1", "unidade 2", "unidade 3"],
    "series_dados": ["tratamento 1", "tratamento 2", "tratamento 3"],
    "dados_extraidos": [
      {{"tratamento": "nome", "parametro": "nome", "valor": "valor com unidade"}},
      {{"tratamento": "nome", "parametro": "nome", "valor": "valor com unidade"}}
    ],
    "valor_maximo": "Qual tratamento/parâmetro teve o maior valor e quanto foi",
    "valor_minimo": "Qual tratamento/parâmetro teve o menor valor e quanto foi",
    "ponto_otimo": "Se identificável, qual dose/tratamento/prática é a mais recomendada",
    "tendencia": "Descrição geral dos padrões nos dados",
    "equacao_regressao": "",
    "significancia_estatistica": "Quais tratamentos diferem estatisticamente entre si e em quais parâmetros",
    "conclusao_principal": "Conclusão prática em 1-2 frases que um agrônomo usaria para fazer uma recomendação"
  }}
]

Se a página NÃO contiver nenhuma tabela real, responda:
[]

IMPORTANTE: Extraia valores numéricos EXATOS. Use o markdown do OCR como referência mas confie mais na imagem visual da página.

Responda APENAS o JSON, sem markdown, sem ```."""


GEMINI_PROMPT_MISTO = """Você é um especialista em agronomia e ciências agrárias. Sua tarefa é extrair o MÁXIMO de informação quantitativa de cada figura e tabela presente nesta página.

Contexto textual extraído da mesma região do PDF:
\"\"\"{contexto}\"\"\"

Texto markdown extraído da(s) tabela(s) pelo OCR (pode conter erros):
\"\"\"{tabelas_md}\"\"\"

Metadados do artigo:
- Título: {titulo}
- Autores: {autores}
- Cultura/Categoria: {cultura}

INSTRUÇÕES:
- Para GRÁFICOS: leia todos os valores dos eixos, identifique cada série pela legenda, extraia pontos de dados, identifique máximos/mínimos/ótimos, transcreva equações de regressão se visíveis
- Para TABELAS: identifique todas colunas/linhas, extraia valores numéricos, compare tratamentos
- Para FOTOS: descreva com detalhes agronômicos

Para CADA elemento visual, responda em JSON (lista):
[
  {{
    "tipo": "grafico_linhas|grafico_barras|grafico_pizza|scatter|tabela|tabela_imagem|foto|diagrama|mapa|outro",
    "titulo_figura": "Título como aparece no PDF",
    "descricao": "Descrição detalhada de 4-8 frases com todos os valores numéricos visíveis",
    "variaveis": ["variável 1 (unidade)", "variável 2 (unidade)"],
    "unidades": ["unidade 1", "unidade 2"],
    "series_dados": ["série/tratamento 1", "série/tratamento 2"],
    "dados_extraidos": [
      {{"serie": "nome", "x": "valor_x", "y": "valor_y"}}
    ],
    "valor_maximo": "Ponto máximo com valores exatos",
    "valor_minimo": "Ponto mínimo com valores exatos",
    "ponto_otimo": "Dose/valor ótimo se identificável",
    "tendencia": "Tendência matemática observada",
    "equacao_regressao": "Equação se visível",
    "significancia_estatistica": "Diferenças estatísticas entre tratamentos",
    "conclusao_principal": "Conclusão prática para recomendação agronômica"
  }}
]

Se a página NÃO contiver nenhum conteúdo visual real, responda: []

Responda APENAS o JSON, sem markdown, sem ```."""


def chamar_gemini(img_path: str, contexto: str, titulo: str, autores: str,
                  cultura: str, tipo_conteudo: str = "imagem", tabelas_md: str = "") -> list:
    """Envia imagem + contexto para Gemini Vision. Retorna lista de figuras/tabelas."""
    with open(img_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")

    # ── Escolher prompt conforme tipo de conteúdo
    if tipo_conteudo == "tabela":
        prompt_template = GEMINI_PROMPT_TABELA
    elif tipo_conteudo == "imagem+tabela":
        prompt_template = GEMINI_PROMPT_MISTO
    else:
        prompt_template = GEMINI_PROMPT_IMAGEM

    prompt = prompt_template.format(
        contexto=contexto[:1500],
        titulo=titulo,
        autores=autores,
        cultura=cultura,
        tabelas_md=tabelas_md[:2000] if tabelas_md else "(não disponível)",
    )

    body = {
        "contents": [{
            "parts": [
                {"inline_data": {"mime_type": "image/png", "data": img_b64}},
                {"text": prompt}
            ]
        }],
        "generationConfig": {
            "temperature": 0.1,
            "maxOutputTokens": 8192,
        }
    }

    resp = requests.post(GEMINI_URL, json=body, timeout=120)
    resp.raise_for_status()
    data = resp.json()

    try:
        text = data["candidates"][0]["content"]["parts"][0]["text"]
    except (KeyError, IndexError):
        print(f"      ⚠️ Resposta inesperada: {data}")
        return []

    # Limpar markdown
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
    if text.endswith("```"):
        text = text.rsplit("```", 1)[0]
    text = text.strip()

    try:
        figuras = json.loads(text)
        if not isinstance(figuras, list):
            figuras = [figuras]
        return figuras
    except json.JSONDecodeError:
        print(f"      ⚠️ JSON inválido: {text[:200]}...")
        return []


# ============================================================
# LOOP PRINCIPAL
# ============================================================
print(f"\n📁 Buscando JSONs em {IMG_DIR}...")
jsons = sorted(IMG_DIR.glob("*-imagens-meta.json"))
print(f"📄 {len(jsons)} JSONs encontrados.")

# ── Reparo automático: resetar páginas marcadas com erro 429
#    (erros de rate limit são temporários, devem ser reprocessados)
total_reparadas = 0
for json_path in jsons:
    with open(json_path, "r", encoding="utf-8") as f:
        meta_reparo = json.load(f)
    reparou = False
    for pag in meta_reparo.get("paginas", []):
        erro = pag.get("gemini_erro", "")
        if "429" in str(erro) or "Too Many Requests" in str(erro):
            pag.pop("gemini_processado", None)
            pag.pop("gemini_erro", None)
            pag.pop("gemini_data", None)
            pag.pop("figuras", None)
            reparou = True
            total_reparadas += 1
    if reparou:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(meta_reparo, f, ensure_ascii=False, indent=2)

if total_reparadas > 0:
    print(f"🔧 {total_reparadas} páginas reparadas (tinham erro 429 de execução anterior)")

total_processadas = 0
total_ja_feitas = 0
total_figuras = 0
total_erros = 0

for json_path in jsons:
    with open(json_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    arquivo_pdf = meta.get("arquivo_pdf", json_path.stem)
    titulo      = meta.get("titulo", "")
    autores     = meta.get("autores", "")
    cultura     = meta.get("cultura", "")
    paginas     = meta.get("paginas", [])

    pendentes = [p for p in paginas if not p.get("gemini_processado", False)]

    if not pendentes:
        total_ja_feitas += len(paginas)
        continue

    print(f"\n{'='*60}")
    print(f"📄 {arquivo_pdf}")
    print(f"  {len(pendentes)} pendentes / {len(paginas)} total")
    print(f"{'='*60}")

    json_modificado = False

    for pag in paginas:
        if pag.get("gemini_processado", False):
            continue

        img_filename = pag["arquivo_imagem"]
        img_path = IMG_DIR / img_filename
        page_no = pag.get("pagina_pdf", "?")
        contexto = pag.get("contexto_textual", "")
        tipo_conteudo = pag.get("tipo_conteudo", "imagem")
        tabelas_md = pag.get("tabelas_markdown", "")

        if not img_path.exists():
            print(f"  ⚠️ p.{page_no} — imagem não encontrada: {img_filename}")
            pag["gemini_processado"] = True
            pag["gemini_erro"] = "imagem não encontrada"
            pag["figuras"] = []
            json_modificado = True
            continue

        print(f"  🔍 p.{page_no} [{tipo_conteudo}] → Gemini...", end=" ", flush=True)

        try:
            figuras = chamar_gemini(
                str(img_path), contexto, titulo, autores, cultura,
                tipo_conteudo=tipo_conteudo, tabelas_md=tabelas_md
            )

            pag["gemini_processado"] = True
            pag["gemini_data"] = datetime.now().isoformat()
            pag["figuras"] = figuras
            json_modificado = True

            if not figuras:
                print(f"📭 nenhuma figura real")
            else:
                print(f"✅ {len(figuras)} figura(s)")
                for fig_idx, fig in enumerate(figuras):
                    print(f"    [{fig_idx+1}] {fig.get('tipo', '?')} — {fig.get('descricao', '')[:80]}...")
                total_figuras += len(figuras)

            total_processadas += 1

        except requests.exceptions.HTTPError as e:
            if e.response is not None and e.response.status_code == 429:
                # Rate limit — NÃO marcar como processado (vai tentar de novo)
                print(f"⏳ Rate limit! Parando este PDF, continua na próxima execução.")
                # Salvar o que já processou deste PDF
                if json_modificado:
                    with open(json_path, "w", encoding="utf-8") as f:
                        json.dump(meta, f, ensure_ascii=False, indent=2)
                    print(f"  💾 JSON salvo (progresso parcial)")
                # Esperar mais tempo e pular para o próximo PDF
                print(f"  ⏳ Aguardando 60s antes de tentar próximo PDF...")
                time.sleep(60)
                break  # sai do loop de páginas deste PDF
            else:
                # Erro HTTP permanente (400, 500, etc) — marcar como processado
                print(f"❌ Erro HTTP: {e}")
                pag["gemini_processado"] = True
                pag["gemini_erro"] = str(e)
                pag["figuras"] = []
                json_modificado = True
                total_erros += 1

        except Exception as e:
            # Erro inesperado (rede, JSON, etc) — marcar como processado
            print(f"❌ Erro: {e}")
            pag["gemini_processado"] = True
            pag["gemini_erro"] = str(e)
            pag["figuras"] = []
            json_modificado = True
            total_erros += 1

        time.sleep(GEMINI_DELAY)

    # Salvar JSON atualizado
    if json_modificado:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
        print(f"  💾 JSON atualizado: {json_path.name}")

# ============================================================
# RESUMO
# ============================================================
print(f"\n{'='*60}")
print(f"🎉 Código 2 concluído!")
print(f"  📷 Páginas processadas agora: {total_processadas}")
print(f"  ⏭️  Já processadas antes: {total_ja_feitas}")
print(f"  🖼️  Figuras descritas: {total_figuras}")
print(f"  ❌ Erros: {total_erros}")
print(f"{'='*60}")

# ============================================================
# REPARO — Resetar páginas com erro 429, timeout ou 503
# ============================================================

import json
from pathlib import Path

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

IMG_DIR = Path("/content/drive/MyDrive/Pdfextractor/data/Imagens")

ERROS_RESETAVEIS = [
    "429",
    "Too Many Requests",
    "Read timed out",
    "timed out",
    "503",
    "Service Unavailable",
]

jsons = sorted(IMG_DIR.glob("*-imagens-meta.json"))
print(f"📄 {len(jsons)} JSONs encontrados.")

total_reparadas = 0
arquivos_afetados = 0

for json_path in jsons:
    with open(json_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    reparou = False
    for pag in meta.get("paginas", []):
        erro = str(pag.get("gemini_erro", ""))
        if any(token in erro for token in ERROS_RESETAVEIS):
            pag.pop("gemini_processado", None)
            pag.pop("gemini_erro", None)
            pag.pop("gemini_data", None)
            pag.pop("figuras", None)
            reparou = True
            total_reparadas += 1

    if reparou:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
        arquivos_afetados += 1
        print(f"  🔧 {json_path.name}")

print(f"\n✅ {total_reparadas} páginas reparadas em {arquivos_afetados} arquivos.")
print(f"   Agora rode o Código 2 novamente.")

"""Vetorização e descrições de imagens"""

# ============================================================
# CÓDIGO 3 — Vetorização de descrições de imagens
# ============================================================
# Lê os JSONs que já têm descrições do Gemini (código 2),
# vetoriza com Qwen3 + OpenSearch sparse, faz upsert no Qdrant.
#
# NÃO chama Gemini, NÃO gasta créditos de API externa.
# Pode rodar várias vezes — nunca re-vetoriza figura já enviada.
#
# INSTALAÇÕES:
# !pip install sentence-transformers transformers torch requests -q
# ============================================================

import os
import json
import uuid
from datetime import datetime
from pathlib import Path

import torch
import requests
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForMaskedLM

# ============================================================
# CONFIGURAÇÕES
# ============================================================
QDRANT_URL         = "https://57eb89f7-8062-4156-8bd9-761b749c9d3b.sa-east-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY     = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.o4SI3QmZtkdOUXK8KVRunQT1SymcxtZrkzUVCXmiZvQ"
COLLECTION_NAME    = "sb100"
DENSE_VECTOR_NAME  = "vetor_denso"
SPARSE_VECTOR_NAME = "vetor_esparso"

# ── Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

BASE_DIR = Path("/content/drive/MyDrive/Pdfextractor")
IMG_DIR  = BASE_DIR / "data" / "Imagens"

# ============================================================
# QDRANT — REST direto
# ============================================================
QDRANT_HEADERS = {
    "api-key": QDRANT_API_KEY,
    "Content-Type": "application/json",
}

def qdrant_put(path, body):
    r = requests.put(f"{QDRANT_URL}{path}", headers=QDRANT_HEADERS, json=body, timeout=60)
    r.raise_for_status()
    return r.json()

def qdrant_get(path):
    r = requests.get(f"{QDRANT_URL}{path}", headers=QDRANT_HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def get_points_count():
    return qdrant_get(f"/collections/{COLLECTION_NAME}")["result"]["points_count"]

def upsert_point(dense_vector, sparse_vector, payload):
    return qdrant_put(f"/collections/{COLLECTION_NAME}/points", {
        "points": [{
            "id": str(uuid.uuid4()),
            "vector": {
                DENSE_VECTOR_NAME: dense_vector,
                SPARSE_VECTOR_NAME: sparse_vector
            },
            "payload": payload
        }]
    })

# ============================================================
# MODELOS DE EMBEDDING
# ============================================================
print("🔄 Carregando modelos de embedding...")
dense_model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")
sparse_tokenizer = AutoTokenizer.from_pretrained(
    "opensearch-project/opensearch-neural-sparse-encoding-doc-v2-distill"
)
sparse_model = AutoModelForMaskedLM.from_pretrained(
    "opensearch-project/opensearch-neural-sparse-encoding-doc-v2-distill"
)
print("✅ Modelos carregados.")

def gerar_vetor_denso(texto: str) -> list:
    return dense_model.encode(texto).tolist()

def gerar_vetor_esparso(texto: str) -> dict:
    tokens = sparse_tokenizer(
        texto, return_tensors='pt',
        max_length=512, truncation=True, padding='max_length'
    )
    with torch.no_grad():
        output = sparse_model(**tokens)
        ativacoes = torch.relu(output.logits)
        max_ativacoes, _ = ativacoes.max(dim=1)
        max_ativacoes = max_ativacoes.squeeze(0)
        indices = (max_ativacoes > 0).nonzero(as_tuple=True)[0].tolist()
        valores = max_ativacoes[indices].tolist()
    if not indices:
        indices = [0]
        valores = [0.0]
    return {"indices": indices, "values": valores}

# ============================================================
# LOOP PRINCIPAL
# ============================================================
print(f"\n📁 Buscando JSONs em {IMG_DIR}...")
jsons = sorted(IMG_DIR.glob("*-imagens-meta.json"))
print(f"📄 {len(jsons)} JSONs encontrados.")
print(f"📊 Qdrant atual: {get_points_count()} pontos")

total_vetorizadas = 0
total_ja_feitas = 0
total_sem_gemini = 0
total_erros = 0

for json_path in jsons:
    with open(json_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    arquivo_pdf = meta.get("arquivo_pdf", json_path.stem)
    titulo      = meta.get("titulo", "")
    autores     = meta.get("autores", "")
    cultura     = meta.get("cultura", "")
    paginas     = meta.get("paginas", [])

    # ── Filtrar: páginas com descrição do Gemini mas ainda não vetorizadas
    pendentes = []
    for pag in paginas:
        if not pag.get("gemini_processado", False):
            total_sem_gemini += 1
            continue
        if pag.get("qdrant_vetorizado", False):
            total_ja_feitas += 1
            continue
        if not pag.get("figuras"):
            # Gemini processou mas não encontrou figuras → marcar como feito
            pag["qdrant_vetorizado"] = True
            continue
        pendentes.append(pag)

    if not pendentes:
        continue

    print(f"\n{'='*60}")
    print(f"📄 {arquivo_pdf}")
    print(f"  {len(pendentes)} páginas para vetorizar")
    print(f"{'='*60}")

    json_modificado = False

    for pag in pendentes:
        page_no = pag.get("pagina_pdf", "?")
        img_filename = pag.get("arquivo_imagem", "")
        contexto = pag.get("contexto_textual", "")
        figuras = pag.get("figuras", [])

        print(f"  📄 p.{page_no} — {len(figuras)} figura(s)")

        erros_pag = 0
        for fig_idx, fig in enumerate(figuras):
            tipo = fig.get("tipo", "outro")
            titulo_fig = fig.get("titulo_figura", "")
            descricao = fig.get("descricao", "")
            variaveis = fig.get("variaveis", [])
            unidades = fig.get("unidades", [])
            series = fig.get("series_dados", [])
            dados = fig.get("dados_extraidos", [])
            valor_max = fig.get("valor_maximo", "")
            valor_min = fig.get("valor_minimo", "")
            ponto_otimo = fig.get("ponto_otimo", "")
            tendencia = fig.get("tendencia", "")
            equacao = fig.get("equacao_regressao", "")
            significancia = fig.get("significancia_estatistica", "")
            conclusao = fig.get("conclusao_principal", "")

            if not descricao:
                continue

            # ── Montar texto rico para vetorização
            partes = [f"[IMAGEM - {tipo}]"]

            if titulo_fig:
                partes.append(f"{titulo_fig}.")

            partes.append(descricao)

            if variaveis:
                partes.append(f"Variáveis: {', '.join(variaveis)}.")
            if series:
                partes.append(f"Séries/tratamentos: {', '.join(series)}.")

            # Incluir dados extraídos como texto (valores exatos para busca)
            if dados:
                pontos_texto = []
                for d in dados[:20]:  # limitar para não estourar o embedding
                    if "serie" in d:
                        pontos_texto.append(f"{d.get('serie','')}: x={d.get('x','')}, y={d.get('y','')}")
                    elif "tratamento" in d:
                        pontos_texto.append(f"{d.get('tratamento','')}: {d.get('parametro','')}={d.get('valor','')}")
                if pontos_texto:
                    partes.append(f"Dados: {'; '.join(pontos_texto)}.")

            if valor_max:
                partes.append(f"Máximo: {valor_max}.")
            if valor_min:
                partes.append(f"Mínimo: {valor_min}.")
            if ponto_otimo:
                partes.append(f"Ponto ótimo: {ponto_otimo}.")
            if tendencia:
                partes.append(f"Tendência: {tendencia}.")
            if equacao:
                partes.append(f"Regressão: {equacao}.")
            if significancia:
                partes.append(f"Significância: {significancia}.")
            if conclusao:
                partes.append(conclusao)

            texto_para_vetor = " ".join(partes).strip()

            print(f"    [{fig_idx+1}] {tipo} ({len(texto_para_vetor)}ch) → ", end="", flush=True)

            try:
                dense_vec = gerar_vetor_denso(texto_para_vetor)
                print("🧠 ", end="", flush=True)

                sparse_vec = gerar_vetor_esparso(texto_para_vetor)
                print(f"🔍({len(sparse_vec['indices'])}) → ", end="", flush=True)

                payload = {
                    "content":          texto_para_vetor,
                    "tipo":             "imagem",
                    "tipo_imagem":      tipo,
                    "titulo_figura":    titulo_fig,
                    "descricao_gemini": descricao,
                    "variaveis":        variaveis,
                    "unidades":         unidades,
                    "series_dados":     series,
                    "dados_extraidos":  dados,
                    "valor_maximo":     valor_max,
                    "valor_minimo":     valor_min,
                    "ponto_otimo":      ponto_otimo,
                    "tendencia":        tendencia,
                    "equacao_regressao": equacao,
                    "significancia":    significancia,
                    "conclusao":        conclusao,

                    "titulo":           titulo,
                    "autores":          autores,
                    "ano":              meta.get("ano", ""),
                    "doi":              meta.get("doi", ""),
                    "periodico":        meta.get("periodico", ""),
                    "cultura":          cultura,
                    "palavras_chave":   meta.get("palavras_chave", ""),

                    "file":             arquivo_pdf,
                    "pagina_pdf":       page_no,
                    "arquivo_imagem":   img_filename,
                    "contexto_textual": contexto[:500],
                    "ingestao":         datetime.now().isoformat(),
                }

                result = upsert_point(dense_vec, sparse_vec, payload)
                print(f"📤 {result['status']}")
                total_vetorizadas += 1

            except Exception as e:
                print(f"❌ {e}")
                erros_pag += 1
                total_erros += 1

        # ── Marcar página como vetorizada
        if erros_pag == 0:
            pag["qdrant_vetorizado"] = True
            pag["qdrant_data"] = datetime.now().isoformat()
            json_modificado = True

    # ── Salvar JSON atualizado
    if json_modificado:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
        print(f"  💾 JSON atualizado: {json_path.name}")

# ============================================================
# RESUMO
# ============================================================
print(f"\n{'='*60}")
print(f"🎉 Código 3 concluído!")
print(f"  📤 Figuras vetorizadas agora: {total_vetorizadas}")
print(f"  ⏭️  Já vetorizadas antes: {total_ja_feitas}")
print(f"  ⏸️  Aguardando Gemini (código 2): {total_sem_gemini}")
print(f"  ❌ Erros: {total_erros}")
print(f"  📊 Total no Qdrant: {get_points_count()} pontos")
print(f"{'='*60}")

# ============================================================
# LISTAR PDFs COM IMAGENS JÁ PROCESSADAS PELO GEMINI
# ============================================================
import json
from pathlib import Path

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

IMG_DIR = Path("/content/drive/MyDrive/Pdfextractor/data/Imagens")

jsons = sorted(IMG_DIR.glob("*-imagens-meta.json"))

completos = []   # todas as páginas processadas
parciais  = []   # algumas páginas processadas
nenhum    = []   # nada processado

for json_path in jsons:
    with open(json_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    paginas = meta.get("paginas", [])
    if not paginas:
        continue

    processadas = sum(1 for p in paginas if p.get("gemini_processado", False))
    total = len(paginas)
    arquivo_pdf = meta.get("arquivo_pdf", json_path.stem)

    if processadas == total:
        completos.append(arquivo_pdf)
    elif processadas > 0:
        parciais.append((arquivo_pdf, processadas, total))
    else:
        nenhum.append(arquivo_pdf)

print(f"✅ {len(completos)} PDFs com TODAS as imagens processadas pelo Gemini:\n")
for nome in completos:
    print(f"  • {nome}")

if parciais:
    print(f"\n⏳ {len(parciais)} PDFs PARCIALMENTE processados:\n")
    for nome, p, t in parciais:
        print(f"  • {nome} ({p}/{t})")

if nenhum:
    print(f"\n❌ {len(nenhum)} PDFs com nenhuma imagem processada")
