version: '3.8'

services:
  frontend:
    build:
      context: ./busca-cientometrica
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend-node
      - backend-python
    restart: always

  backend-node:
    build:
      context: ./api-cientometria
      dockerfile: Dockerfile.node
    ports:
      - "5001:5001"
    volumes:
      - ./api-cientometria/documents:/app/documents
      - ./api-cientometria/api.db:/app/api.db
      - "./api-cientometria/Consolidado - Respostas Gerais.xlsx:/app/Consolidado - Respostas Gerais.xlsx"
    environment:
      - PORT=5001
      - API_BASE_URL=http://backend-python:8000
    env_file:
      - ./api-cientometria/.env
    restart: always

  backend-python:
    build:
      context: ./api-cientometria
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - ./api-cientometria/.env
    restart: always
